### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by trangdata**
Work in progress.

### CODE REVIEW

**Comment by trangdata** [comment]
I think we should separate the simulation code into a different package for modularity.

**Comment by trangdata** [comment]
@brett-mckinney I'm running into errors while trying to run the `npdr_Ex.R`. Do you know where `testdata10` is?

**Comment by brett-mckinney** [comment]
I am not familiar with npdr_Ex.R. I don't have that file anywhere. testdata10 is from Rinbix, a different project. I don't have the testdata10 file associated with the npdr project. Here is testdata10.rda.
https://github.com/insilico/Rinbix/tree/master/data


________________________________

**Comment by trangdata** [comment]
I see. So do we need [`inbixGAIN.R`](https://github.com/insilico/npdr/blob/master/R/inbixGAIN.R) at all?

**Comment by trangdata** [comment]
Also, do we know what `attr.range` should be? We use it [here](https://github.com/insilico/npdr/blob/51c2415677c20a1345da6d98b475d6a0daff6bb1/R/nearestNeighbors.R#L63) but we may have had removed its definition.

**Comment by brett-mckinney** [comment]
It should be the following, but we can just use the code body rather than define a function since it's just one line.

attr.range <- function(my.mat) {
  # compute denominator of the diff formula
  # for each attribute x (column) in my.mat, max(x) -  min(x)
  apply(as.matrix(my.mat), 2, function(x) {max(x) - min(x)})
}

**Comment by trangdata** [comment]
@brett-mckinney A few final questions for this PR:
- Where is `getEigenValues`? Is it in [`arma_getEigenValues.cpp`](https://github.com/insilico/npdr/blob/master/R/arma_getEigenValues.cpp)? I'm unsure how the {Rcpp} package works, but do we need any additional files that tell R to use `getEigenValues` from this cpp code?
- Do we need [`inbixGAIN.R`](https://github.com/insilico/npdr/blob/master/R/inbixGAIN.R)?

**Comment by brett-mckinney** [comment]
> I think we should separate the simulation code into a different package for modularity.

**Comment by brett-mckinney** [comment]
Yes, getEigenValues is in the .cpp. The function is just a call to Armadillo to speed up an eigenvector calculation in simultion2.R that ensures simulated correlation matrices are positive definite. Some users will have trouble with Rcpp, so the cpp part is optional but we should keep it. We made major changes to the simulation methods a couple years ago that probably need to be published. Might separate out the simulation methods in the future but keep here for now.

Let's keep inbixGAIN.R. I use its functions in inst/ and I need its functions from time to time. It's useful for understanding the output of interaction simulations (among other things). I haven't decided long-term what I am going to do with the Rinbix library, so I just pulled this pure-R code into npdr (other parts of Rinbix have some c++ dependence).

**Comment by trangdata** [comment]
~OK so how do I let the package know that the getEigenValues function comes from the .cpp script?~

**_Update_**: I figured it out: https://r-pkgs.org/src.html. Took me a while to debug a few things (install fortran, updating both Rcpp and RcppArmadillo) but it seems to work now.

**Comment by trangdata** [comment]
These changes made the package pass CRAN checks but there are still larger items on the TODO list (I'll make an issue for this):
- modularize the code (e.g. move simulation function elsewhere, break down functions with more than 500 lines of code, etc.)
- create examples that **work** (hopefully independent of the data simulation step, move the examples from `inst` to `vignettes`)

**Pull request merged**
